api_platform:
    formats:
        json:     ['application/json']
        csv:      ['text/csv']
        html:     ['text/html']
        jsonld:   ['application/ld+json']
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
