<?php
/**
 * StudentApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Server
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use OpenAPI\Server\Model\Student;

/**
 * StudentApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  OpenAPI\Server\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface StudentApiInterface
{

    /**
     * Operation deleteStudentItem
     *
     * Removes the Student resource.
     *
     * @param  string $id   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function deleteStudentItem($id, &$responseCode, array &$responseHeaders);

    /**
     * Operation getStudentCollection
     *
     * Retrieves the collection of Student resources.
     *
     * @param  int $page  The collection page number (optional, default to 1)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\Student[]
     *
     */
    public function getStudentCollection($page = 1, &$responseCode, array &$responseHeaders);

    /**
     * Operation getStudentItem
     *
     * Retrieves a Student resource.
     *
     * @param  string $id   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\Student
     *
     */
    public function getStudentItem($id, &$responseCode, array &$responseHeaders);

    /**
     * Operation patchStudentItem
     *
     * Updates the Student resource.
     *
     * @param  string $id   (required)
     * @param  OpenAPI\Server\Model\Student $student  The updated Student resource (optional)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\Student
     *
     */
    public function patchStudentItem($id, Student $student = null, &$responseCode, array &$responseHeaders);

    /**
     * Operation postStudentCollection
     *
     * Creates a Student resource.
     *
     * @param  OpenAPI\Server\Model\Student $student  The new Student resource (optional)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\Student
     *
     */
    public function postStudentCollection(Student $student = null, &$responseCode, array &$responseHeaders);

    /**
     * Operation putStudentItem
     *
     * Replaces the Student resource.
     *
     * @param  string $id   (required)
     * @param  OpenAPI\Server\Model\Student $student  The updated Student resource (optional)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\Student
     *
     */
    public function putStudentItem($id, Student $student = null, &$responseCode, array &$responseHeaders);
}
